const RSS_FEEDS = [
 'https://news.google.com/rss/search?q=Viktor+Orban',


  // 🌐 Angol nyelvű hírek
  'http://feeds.bbci.co.uk/news/world/rss.xml',
  'http://rss.cnn.com/rss/edition_world.rss',
  'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
  'https://www.aljazeera.com/xml/rss/all.xml',
  'https://rss.dw.com/rdf/rss-en-top',
  'http://feeds.skynews.com/feeds/rss/world.xml',
  'https://www.theguardian.com/world/rss',
  'https://feeds.npr.org/1004/rss.xml',
  'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
  'https://www.france24.com/en/rss',
  'https://rss.cbc.ca/lineup/world.xml',
  'https://www.latimes.com/world-nation/rss2.0.xml',
  'https://www.channelnewsasia.com/rssfeeds/8395986',
  'https://www.washingtontimes.com/rss/headlines/news/world/',
  'https://www.japantimes.co.jp/feed/',
  'https://www.thehindu.com/news/international/feeder/default.rss',
  'https://www.smh.com.au/rss/feed.xml',
  'https://www.rfi.fr/en/rss',
  'https://www.politico.eu/feed/',
  'https://www.ft.com/?format=rss',
  'http://www.independent.co.uk/news/world/rss',
  'https://www.abc.net.au/news/feed/51120/rss.xml',
  'https://moxie.foxnews.com/google-publisher/world.xml',
  'https://moxie.foxnews.com/google-publisher/politics.xml',
  'https://globalnews.ca/world/feed/',

  // 🇺🇦 Ukrán hírek
  'https://www.pravda.com.ua/rss/',
  'https://www.ukrinform.ua/rss',
  'https://24tv.ua/rss/all.xml',
  'https://nv.ua/ukr/rss/all.xml',
  'https://www.unian.net/rss',
  'https://tsn.ua/rss',
  'https://www.ukrinform.net/rss',
  'https://www.kyivpost.com/feed',
  'https://glavred.info/rss.xml',
  'https://www.liga.net/news/rss.xml',
  'https://espreso.tv/rss',

   // Japan
  'https://www3.nhk.or.jp/rss/news/cat0.xml',
  'https://www.japantimes.co.jp/feed/',
  'https://www.asahi.com/rss/asahi/newsheadlines.rdf',

  // China
  'https://www.chinadaily.com.cn/rss/china_rss.xml',
  'https://www.ecns.cn/rss/rss.xml',
  'https://www.scmp.com/rss/91/feed',
  'https://www.whatsonweibo.com/feed/',
  
  // India
  'https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms',
  'https://www.thehindu.com/news/international/feeder/default.rss',
  'https://www.indiatoday.in/rss/home',

  // Spain
  'https://www.abc.es/rss/feeds/abc_Internacional.xml',
  'https://elpais.com/rss/feed.html?feedId=1022',
  'https://www.elmundo.es/rss/espana.xml',
  'https://www.europapress.es/rss/rss.aspx',
  'https://www.eldiario.es/rss/',
  'https://www.20minutos.es/rss/internacional/',
  'https://okdiario.com/rss',

   // Israel
  'https://www.jpost.com/Rss/RssFeedsHeadlines.aspx',
  'https://www.israelhayom.com/feed/',
  'https://www.middleeasteye.net/rss',
  'https://www.al-monitor.com/rss',
  
  // Russia
  'https://www.rt.com/rss/news/',
  'https://www.interfax.ru/rss.asp',
  'https://russian.rt.com/rss',
  'https://www.mk.ru/rss/news/index.xml',
  'https://ria.ru/export/rss2/archive/index.xml',
  'https://tass.com/rss/v2.xml',
  'https://lenta.ru/rss',
  'https://rssexport.rbc.ru/rbcnews/news/30/full.rss',

  // France
  'https://www.france24.com/fr/rss',
  'https://www.francetvinfo.fr/titres.rss',
  'https://www.lemonde.fr/rss/une.xml',
  'https://www.lefigaro.fr/rss/figaro_actualites.xml',
  'https://www.liberation.fr/arc/outboundfeeds/rss-all/',
  'https://www.la-croix.com/rss',
  'https://www.rfi.fr/fr/rss',

  // Germany
  'https://www.tagesschau.de/xml/rss2',
  'https://www.spiegel.de/international/index.rss',
  'https://www.faz.net/rss/aktuell/',
  'https://www.welt.de/feeds/topnews.rss',
  'https://www.n-tv.de/rss',
  'https://taz.de/!p4608;rss/',
  'https://rss.dw.com/rdf/rss-de-all',
  'https://newsfeed.zeit.de/index',
  'https://www.welt.de/feeds/latest.rss',

  // Turkey
  'https://www.hurriyet.com.tr/rss/anasayfa',
  'https://www.sozcu.com.tr/rss.xml',
  'https://www.cumhuriyet.com.tr/rss/1.xml',
  'https://www.aa.com.tr/tr/rss/default?cat=guncel',
  'https://www.yenisafak.com/rss',
  'https://www.trthaber.com/manset_articles.rss',
  'https://www.turkiyegazetesi.com.tr/rss/rss.xml',

  // Iran
  'https://www.tehrantimes.com/rss',
  'https://en.farsnews.ir/rss',
  'https://www.al-monitor.com/rss',
  'https://www.isna.ir/rss',
  'https://financialtribune.com/rss',
  'https://kayhan.ir/fa/rss/allnews',
  'https://en.abna24.com/rss.xml',

  // Brazil
  'https://g1.globo.com/dynamo/rss2.xml',
  'https://www.uol.com.br/feed/',
  'https://www.folha.uol.com.br/rss/feed.xml',
  'https://rss.estadao.com.br/cidades.xml',
  'https://www.cnnbrasil.com.br/rss',
  'https://oglobo.globo.com/rss.xml',
  'https://www.bbc.com/portuguese/topics/cyx5krnw38vt/index.xml',
  'https://exame.com/feed/',
  'https://www.correiobraziliense.com.br/rss',
  'https://veja.abril.com.br/rss/',

  // Italy
  'https://www.repubblica.it/rss/homepage/rss2.0.xml',
  'https://www.corriere.it/rss/homepage.xml',
  'https://www.ilsole24ore.com/rss/notizie.xml',
  'https://www.lastampa.it/rss.xml',
  'https://www.ilfattoquotidiano.it/feed/',
  'https://www.rainews.it/dl/rainews/TGR/basic/RSS.xml',
  'https://www.ansa.it/sito/ansait_rss.xml',
  'https://www.tgcom24.mediaset.it/rss/homepage.xml',
  'https://www.avvenire.it/rss/attualita.xml',
  'https://www.huffingtonpost.it/rss.xml',
  'https://www.ilgiornale.it/rss.xml',

  // United Kingdom
  'https://www.bbc.co.uk/news/10628494',
  'https://rss.theguardian.com/world/rss',
  'https://www.telegraph.co.uk/news/worldnews/rss.xml',
  'https://www.independent.co.uk/news/world/rss',
  'https://www.dailymail.co.uk/news/worldnews/index.rss',
  'https://www.thetimes.co.uk/environment/rss',
  'https://news.sky.com/feeds/rss/world.xml',
  'https://www.express.co.uk/news/world/rss',
  'https://metro.co.uk/news/world/feed/',
  'https://www.mirror.co.uk/news/world-news/rss.xml',

  // United States
  'https://rss.nytimes.com/services/xml/rss/nyt/World.xml',
  'https://feeds.washingtonpost.com/rss/world',
  'https://www.wsj.com/xml/rss/3_7085.xml',
  'https://www.npr.org/rss/rss.php?id=1004',
  'https://www.cnn.com/rss/edition_world.rss',
  'https://feeds.foxnews.com/foxnews/world',
  'https://www.nbcnews.com/id/3032506/device/rss/rss.xml',
  'https://abcnews.go.com/abcnews/internationalheadlines',
  'https://www.latimes.com/world/rss2.0.xml',
  'https://www.voanews.com/api/epiqqe$eviqq',

  // Poland
  'https://www.tvn24.pl/najnowsze.xml',
  'https://www.rmf24.pl/fakty/polska/feed',
  'https://www.polskieradio.pl/rss.aspx?id=156',
  'https://www.gazetaprawna.pl/rss',
  'https://wiadomosci.wp.pl/rss.xml',
  'https://www.money.pl/rss.xml',
  'https://www.polsatnews.pl/rss/wszystkie.xml',
  'https://www.dziennik.pl/rss/wydarzenia.xml',
  'https://www.rp.pl/rss',
  'https://www.onet.pl/rss.xml',
  
  // Austria
  'https://www.diepresse.com/feed/rss',
  'https://www.derstandard.at/rss',
  'https://kurier.at/feeds/rss',
  'https://www.oe24.at/rss',
  'https://www.tt.com/rss',
  'https://www.sn.at/rss',
  'https://www.vol.at/feed',
  'https://orf.at/rss/',
  'https://www.krone.at/rss',
  'https://www.nachrichten.at/nachrichten/rss',

  // Czech Republic
  'https://www.idnes.cz/rss.aspx?c=zpravodaj',
  'https://www.novinky.cz/rss/',
  'https://www.lidovky.cz/rss.aspx?c=zpravy',
  'https://zpravy.aktualne.cz/rss/',
  'https://denikn.cz/feed/',
  'https://echo24.cz/rss',
  'https://www.parlamentnilisty.cz/export/rss.aspx',
  'https://www.tyden.cz/rss/',
  'https://www.ceskenoviny.cz/rss/zpravy.xml',
  'https://www.reflex.cz/rss/',
  
  // Switzerland
  'https://www.nzz.ch/rss',
  'https://www.tagesanzeiger.ch/rss',
  'https://www.20min.ch/rss/rss.tmpl?type=news',
  'https://www.swissinfo.ch/service/rss/rss.rdf',
  'https://www.blick.ch/news/rss.xml',
  'https://www.derbund.ch/rss',
  'https://www.letemps.ch/rss',
  'https://www.rts.ch/tools/rss/',
  'https://www.laliberte.ch/feed',
  'https://www.arcinfo.ch/rss',
  
  // Serbia
  'https://www.rts.rs/page/stories/sr/rss.html',
  'https://www.blic.rs/rss',
  'https://www.novosti.rs/rss',
  'https://www.danas.rs/feed/',
  'https://www.kurir.rs/rss',
  'https://n1info.rs/feed/',
  'https://www.politika.rs/rss',
  'https://www.telegraf.rs/rss',
  'https://rs.n1info.com/rss/svet/',
  'https://nova.rs/feed/',

  // Estonia
  'https://news.err.ee/rss',
  'https://estonianworld.com/feed/',
  'https://bnn-news.com/feed',
  'https://balticnews.com/feed',
  'https://estonianfreepress.com/feed/',
  'https://www.postimees.ee/rss',
  'https://epl.delfi.ee/rss',
  'https://arileht.delfi.ee/rss',
  'https://maaleht.delfi.ee/rss',
  'https://www.ohtuleht.ee/rss',
  
  // Latvia
  'https://eng.lsm.lv/rss/',
  'https://www.baltictimes.com/rss/',
  'https://www.delfi.lv/rss/',
  'https://www.tvnet.lv/rss',
  'https://www.apollo.lv/rss',
  'https://nra.lv/rss/',
  'https://jauns.lv/rss',
  'https://bnn-news.com/feed',
  'https://www.la.lv/rss',
  'https://lvportals.lv/rss',
  
  // Lithuania
  'https://www.lrt.lt/rss/naujienos',
  'https://www.delfi.lt/rss/',
  'https://www.15min.lt/rss',
  'https://www.lrytas.lt/rss',
  'https://www.alfa.lt/rss',
  'https://kauno.diena.lt/rss',
  'https://klaipeda.diena.lt/rss',
  'https://www.tv3.lt/rss',
  'https://ve.lt/rss',
  'https://www.vz.lt/rss',
  
  // Croatia
  'https://www.index.hr/rss/',
  'https://www.vecernji.hr/rss',
  'https://www.jutarnji.hr/rss',
  'https://dnevnik.hr/rss',
  'https://www.24sata.hr/feeds/rss',
  'https://www.tportal.hr/rss',
  'https://www.hrt.hr/rss',
  'https://www.nacional.hr/feed/',
  'https://www.slobodnadalmacija.hr/rss',
  'https://www.telegram.hr/feed/',
  
  // Slovenia
  'https://www.rtvslo.si/rss/slovenija',
  'https://www.delo.si/rss',
  'https://www.dnevnik.si/rss',
  'https://www.vecer.com/rss',
  'https://siol.net/rss',
  'https://www.mladina.si/rss',
  'https://nova24tv.si/feed/',
  'https://www.domovina.je/feed/',
  'https://www.primorske.si/rss',
  'https://www.slovenskenovice.si/rss',
  
  // Bosnia and Herzegovina
  'https://www.klix.ba/rss',
  'https://www.avaz.ba/rss',
  'https://www.nezavisne.com/rss',
  'https://www.bljesak.info/feed',
  'https://ba.n1info.com/rss/',
  'https://www.oslobodjenje.ba/rss',
  'https://rtvbn.com/rss',
  'https://radiobrcko.ba/feed/',
  'https://bhrt.ba/feed/',
  'https://cazin.net/rss',
  
  // North Macedonia
  'https://www.slobodenpecat.mk/feed/',
  'https://fokus.mk/feed/',
  'https://a1on.mk/feed/',
  'https://www.24.mk/rss',
  'https://makfax.com.mk/feed/',
  'https://republika.mk/feed/',
  'https://press24.mk/rss.xml',
  'https://vecer.mk/feed/',
  'https://www.mkd.mk/mk/feed',
  'https://sitel.com.mk/rss.xml',
  
  // Albania
  'https://top-channel.tv/rss/',
  'https://www.balkanweb.com/feed/',
  'https://www.oranews.tv/rss',
  'https://www.gazetatema.net/feed/',
  'https://abcnews.al/feed/',
  'https://www.rtsh.al/feed/',
  'https://www.panorama.com.al/feed/',
  'https://report-tv.al/feed/',
  'https://newsbomb.al/feed/',
  'https://lapsi.al/feed/',
  
  // Montenegro
  'https://www.vijesti.me/rss',
  'https://www.cdm.me/feed/',
  'https://rtcg.me/rss.html',
  'https://www.dan.co.me/rss',
  'https://www.antenam.net/rss',
  'https://www.portalanalitika.me/rss',
  'https://www.in4s.net/feed/',
  'https://www.monitor.co.me/feed/',
  'https://mnemagazin.me/feed/',
  'https://www.pobjeda.me/rss',
  
  // Bulgaria
  'https://www.dnevnik.bg/rss.php',
  'https://www.novinite.com/rss.php',
  'https://www.bnr.bg/rss',
  'https://www.trud.bg/rss/',
  'https://fakti.bg/rss',
  'https://www.segabg.com/rss',
  'https://dariknews.bg/rss',
  'https://nova.bg/rss',
  'https://www.24chasa.bg/rss/',
  'https://offnews.bg/rss',

  // Belgium / Brussels
  'https://www.brusselstimes.com/feed',
  'https://www.politico.eu/feed/',
  'https://www.euractiv.com/feed/',
  'https://www.europeaninterest.eu/feed/',
  'https://www.eubusiness.com/news/RSS',
  'https://www.vrt.be/vrtnws/en.rss.articles.xml',
  'https://www.rtbf.be/info/rss',
  'https://www.lalibre.be/rss',
  'https://www.lesoir.be/rss',
  'https://www.deredactie.be/cm/vrtnieuws.net/RSS',
  
  // 🇭🇺 Magyar hírek
  'https://index.hu/24ora/rss/',
  'https://mandiner.hu/rss'
];
module.exports = RSS_FEEDS;
