name: Add activation columns to users table

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install sqlite3
        run: npm install sqlite3

      - name: Run migration script
        run: node migrations/add_activation_columns.js

      - name: Commit DB changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add newsbot.sqlite
          git commit -m "Add activation_token and activation_expires_at columns"
          git push
