name: Teszt emailes regisztr치ci칩

on:
  workflow_dispatch:

jobs:
  test-register:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install sqlite3 nodemailer

      - name: Run dummy register (regisztr치ci칩s teszt)
        run: node pages/api/register.ts
