name: Import RSS feeds into SQLite

on:
  workflow_dispatch:  # Manuálisan indítható

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Init DB
        run: node init_db.js

      - name: Import feeds
        run: node import_feeds.js

      - name: Commit SQLite DB
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add newsbot.sqlite
          git commit -m "Update SQLite with latest RSS feeds" || echo "No changes"
          git push
